services:
  - type: web
    name: symfony-app
    env: docker
    plan: free
    region: oregon  # ou frankfurt si tu veux un hébergement en Europe
    branch: main
    repo: https://github.com/rasere/rasere.git
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
